### PR TITLE
Support null bytes in stored/retrieved data

### PR DESCRIPTION
**Pull request by felixbuenemann**
Before this fix `spp_feed` was using `hbuf_puts`, which due to it's usage of `strlen` could not handle data containing null bytes. This changes `spp_feed` to pass the size obtained in python through to hbuf_put.

This fixes issue #1.

### CODE REVIEW

**Comment by hit9** [comment]
Thanks!

**Comment by felixbuenemann** [comment]
Thanks for merging and this nice library. Please ping me once you've released a new package.

**Comment by hit9** [comment]
@felixbuenemann spp_py@0.0.7 and ssdb.py@0.1.8 released.

**Comment by felixbuenemann** [comment]
Thank you! :tada:

**Pull request merged**
